syntax = "proto3";

package auth;

option go_package = "github.com/pnaskardev/URL-Shortner-V1/url-shortner-rpc/auth";

// Service encapsulating all Auth related methods
service Auth {
  // SignIn Request
  rpc SignIn (SignInRequest) returns (SignInResponse) {}

  // SignUp Request
  rpc SignUp (SignUpRequest) returns (SignUpResponse) {}
}

// SignUp Request with username and password
message SignUpRequest {
  string username = 1;
  string password = 2;
}

// SignUpResponse
message SignUpResponse{
  bool success=1;
  bool message =2;
}

message SignInRequest {
  string username=1;
  string password=2;
}

message SignInResponse {
  bool success=1;
  string message=2;
  string jwt_key=3;
}

// // The request message containing the user's name.
// message HelloRequest {
//   string name = 1;
// }

// // The response message containing the greetings
// message HelloReply {
//   string message = 1;
// }